### ISSUE TITLE
How can I obtain the dataset  for DDS?

### ISSUE THREAD

**Issue by LouisYZK** [AudioVisualEmotionChallenge/AVEC2019#2]
Excuse me, I have searched throgh the AVEC2019 workshop and baseline paper for a long time, still I didn't get the way to obtain the data set for DDS.

**Comment by AudioVisualEmotionChallenge** [comment]
Hi, the DAIC-WOZ dataset - http://dcapswoz.ict.usc.edu/ - and its extended version used in AVEC 2019 are owned by USC. You can send your request to Mohammad Soleymani, and Jill Boberg.
