### ISSUE TITLE
How to obtained the dataset?

### ISSUE THREAD

**Issue by shamanez** [AudioVisualEmotionChallenge/AVEC2019#4]

**Comment by AudioVisualEmotionChallenge** [comment]
Hi, requests for data access shall be send to the respective data owner, i.e., University of Southern California for the Depression dataset - cf. https://www.ihp-lab.org/resources/, Ulm University (Eva Maria Messner is the contact person) for the State-of-Mind dataset, and Imperial College London for the SEWA dataset - cf. https://db.sewaproject.eu/. We will be working in the near future to have a central website clarifying such aspects for the different AVEC challenges that have been running so far.
