### ISSUE TITLE
Dataset and annotations for CES partition

### ISSUE THREAD

**Issue by kkusumam** [AudioVisualEmotionChallenge/AVEC2019#6]
Hi, I am trying to access the CES partition for 2019 challenge and have also tried signing up for the data download. Could you please let me know how I can access the partition along with the combined annotations (gold standard) from different raters for the CES challenge?

**Comment by kkusumam** [comment]
Got the data

**Comment by scbqwe** [comment]
> Got the data

Hi, I has obtained the account for data download in SEWA website(https://db.sewaproject.eu/search/). Now i get the same problem mentioned above. How can i access the CES partition along with the combined annotations (gold standard) from different raters for the CES challenge? Thank you.
